#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run build
npm run build

# Check if there are any uncommitted changes
if [ -n "$(git status --porcelain)" ]; then
  echo "Error: There are uncommitted changes after build. Please commit these changes before pushing."
  exit 1
fi 